#ifndef BUTTON_MODES_H
#define BUTTON_MODES_H

typedef enum
{
    SWITCH_TYPE_TOGGLE,
    SWITCH_TYPE_MOMENTARY,
    SWITCH_TYPE_MULTIFUNCTION
} SwitchType;


typedef enum
{
    SWITCH_MODE_UNLINKED,
    SWITCH_MODE_FRONT,
    SWITCH_MODE_SINGLE,
    SWITCH_MODE_DOUBLE,
    SWITCH_MODE_TRIPPLE,
    SWITCH_MODE_LONG,
} LocalSwitchMode;


#endif //BUTTON_MODES_H
