#ifndef BUTTON_MODES_H
#define BUTTON_MODES_H

typedef enum
{
    SWITCH_MODE_UNLINKED,
    SWITCH_MODE_FRONT,
    SWITCH_MODE_SINGLE,
    SWITCH_MODE_DOUBLE,
    SWITCH_MODE_TRIPPLE,
    SWITCH_MODE_LONG,
} LocalSwitchMode;

typedef enum
{
    BUTTON_MODE_SIMPLE,
    BUTTON_MODE_SMART,
} ButtonMode;


#endif //BUTTON_MODES_H
