name: Build

on:
  workflow_dispatch:
  push:

env:
  TARGET: HelloZigbee.ota
  BUILD_DIR: build
  ARTIFACT_DIR: build/src
  TOOLCHAIN_DIR: toolchain

jobs:
  firmware:
    strategy:
      matrix:
        board: ["EBYTE_E75", "QBKG11LM", "QBKG12LM"]
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Get toolchain
        run: |
          mkdir -p ${{github.workspace}}/${{ env.TOOLCHAIN_DIR }} && \
          wget https://github.com/openlumi/BA2-toolchain/releases/download/20201219/ba-toolchain-20201219.tar.bz2 -O - | tar -jx -C ${{github.workspace}}/${{ env.TOOLCHAIN_DIR }}
      - name: Install extra libs
        run: |
          pip3 install xmltodict pycryptodome && \
          sudo apt install libfl2
      - name: List directory
        run: ls -Rla ${{github.workspace}}
      - name: Configure CMake
        id: configure
        run: |
          cmake -B ${{github.workspace}}/build -DTOOLCHAIN_PREFIX=$(realpath ${{github.workspace}}/${{ env.TOOLCHAIN_DIR }}/ba-toolchain) -DBUILD_NUMBER=${{github.run_number}} -DBOARD=${{matrix.board}}
      - name: Build
        id: build
        run: |
          cmake --build ${{github.workspace}}/build --target ${{ env.TARGET }} -j$(($(nproc)+1))
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          # Artifact name
          name: hello_zigbee_${{matrix.board}}_${{github.run_number}}
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            ${{github.workspace}}/${{ env.ARTIFACT_DIR }}/*.bin
            ${{github.workspace}}/${{ env.ARTIFACT_DIR }}/*.ota
